apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

namespace:  sc-rima-prod
namePrefix: soco-
commonLabels:
  owner: sc
  stage: prod
  app.kubernetes.io/instance: rima-sc-prod
  app.kubernetes.io/version: master
commonAnnotations:
  contact: "Ralf Berger <ralf.berger@uni-due.de>"

secretGenerator:
- name: configuration
  env: configuration.env
images:
- name: inko/soco-rima-frontend
  newName: socialcomputing/rima-frontend
  newTag: "0.0.12"
- name: inko/soco-rima-backend
  newName: socialcomputing/rima-backend
  newTag: "0.0.12"
- name: inko/soco-rima-model-downloader
  newName: socialcomputing/rima-model-downloader
  newTag: "0.0.12"
- name: inko/soco-rima-model-server
  newName: socialcomputing/rima-model-server
  newTag: "0.0.12"
- name: redis
  newTag: "6.2.7-alpine"
- name: postgres
  newName: bitnami/postgresql
  newTag: "13.6.0"
