- op:    replace
  path:  /spec/replicas
  value: 1
- op:    replace
  path:  "/metadata/annotations/keel.sh~1policy"
  value: force
- op:    add
  path:  "/metadata/annotations/keel.sh~1match-tag"
  value: true
