apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

namespace:  sc-rima-dev-alp
namePrefix: soco-
commonLabels:
  owner: sc
  stage: dev
  app.kubernetes.io/instance: rima-sc-dev-alp
  app.kubernetes.io/version: master
commonAnnotations:
  contact: "Ralf Berger <ralf.berger@uni-due.de>"

patchesJson6902:
- target:
    group: networking.k8s.io
    version: v1beta1
    kind: Ingress
    name: web
  path: ingress.patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: api
  path: deployment.patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: web
  path: deployment.patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: api
  path: deployment.patch.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    name: worker
  path: deployment.patch.yaml

secretGenerator:
- name: configuration
  env: configuration.env

images:
- name: inko/soco-rima-frontend
  newName: socialcomputing/rima-frontend
  newTag: dev-alp
- name: inko/soco-rima-backend
  newName: socialcomputing/rima-backend
  newTag: dev-alp
- name: inko/soco-rima-model-downloader
  newName: socialcomputing/rima-model-downloader
  newTag: dev-alp
- name: inko/soco-rima-model-server
  newName: socialcomputing/rima-model-server
  newTag: dev-alp
- name: redis
  newTag: "6.2"
- name: postgres
  newName: bitnami/postgresql
  newTag: "13.6.0"
